### ISSUE TITLE
Any plans?

### ISSUE THREAD

**Issue by sebshot** [tcarrio/gpmodbot#1]
will this ever work 😢

**Comment by tcarrio** [comment]
Unfortunately after reviewing the Terms of Service for Google Play, this excerpt makes it an absolute breach of the terms to use in a streaming service:

> You may not use Content as part of any service for sharing, lending or **multi-person use**, or for the purpose of any other institution, except as specifically permitted and only in the exact manner specified and enabled by Google (for example, through “Social Recommendations”). 

Even if this service were to be finalized, use of it in any room with more users than the subscriber would be a breach of the ToS and likely resulting in disabling of your account. Due to this I've discontinued plans for continued development.
